# Étape3️⃣ Chargement des Données via SQLAlchemy

Configurer la connexion

In [35]:
import os
from dotenv import load_dotenv
from sqlalchemy import create_engine

load_dotenv()

user = os.getenv("DB_USER")
password = os.getenv("DB_PASSWORD")
host = os.getenv("DB_HOST")
database = os.getenv("DB_NAME")

engine = create_engine(
    f"postgresql+psycopg2://{user}:{password}@{host}:5432/{database}"
)

conn = engine.connect()
print("Connexion réussie")
conn.close()

Connexion réussie

Séparer le dataset CSV selon les tables normalisées

In [36]:
import pandas as pd

df = pd.read_csv("financecore_clean.csv")

In [37]:
#Clients
clients_df = df[[
    'client_id',
    'score_credit_client',
    'segment_client',
    'categorie_risque'
]].drop_duplicates()

#Segments
segments_df = df[['segment_client']].drop_duplicates().reset_index(drop=True)
segments_df['segment_id'] = segments_df.index + 1

comptes_df = df[[
    'client_id',
    'solde_avant'
]].drop_duplicates()

comptes_df = comptes_df.reset_index(drop=True)
comptes_df['compte_id'] = comptes_df.index + 1

comptes_df = comptes_df[[
    'compte_id',
    'client_id',
    'solde_avant'
]]

print(comptes_df.head())
#Produits
produits_df = df[['produit']].drop_duplicates()
produits_df = produits_df.rename(columns={'produit': 'nom_produit'})

#Agences
agences_df = df[['agence']].drop_duplicates()
agences_df = agences_df.rename(columns={'agence': 'nom_agence'})

#Temps
temps_df = df[[
    'date_transaction',
    'annee',
    'mois',
    'trimestre',
    'jour_semaine'
]].drop_duplicates()

#Transactions (table principale)
transactions_df = df[[
    'transaction_id',
    'client_id',
    'date_transaction',
    'montant',
    'devise',
    'taux_change_eur',
    'montant_eur',
    'categorie',
    'produit',
    'agence',
    'type_operation',
    'statut',
    'score_credit_client',
    'segment_client',
    'solde_avant',
    'is_outlier_montant',
    'is_outlier_score',
    'is_anomaly',
    'annee',
    'mois',
    'trimestre',
    'jour_semaine',
    'montant_eur_verifie',
    'montant_eur_match',
    'categorie_risque',
    'montant_credit',
    'montant_debit',
    'rejet'
]].copy()

print(clients_df.shape)
print(transactions_df.shape)

   compte_id client_id  solde_avant
0          1   CLI0060     16415.10
1          2   CLI0057     42890.81
2          3   CLI0015     48489.38
3          4   CLI0045     43962.51
4          5   CLI0034     17312.83
(289, 4)
(2000, 28)

Insérer les données

In [38]:
# Segments
segments_df.to_sql('segments', engine, if_exists='replace', index=False)

# Produits
produits_df.to_sql('produits', engine, if_exists='append', index=False)

# Agences
agences_df.to_sql('agences', engine, if_exists='append', index=False)

# Temps
temps_df.to_sql('temps', engine, if_exists='append', index=False)

# Clients
clients_df.to_sql('clients', engine, if_exists='append', index=False)

# Transactions
transactions_df.to_sql('transactions', engine, if_exists='append', index=False)

# Comptes 
comptes_df.to_sql('comptes', engine, if_exists='append', index=False)

print("Insertion terminée")

Insertion terminée

 Gestion des conflits lors de l’insertion des données

In [39]:
from sqlalchemy import text

query_client = text("""
INSERT INTO public.clients (client_id, score_credit_client, segment_client, categorie_risque)
VALUES (:client_id, :score_credit_client, :segment_client, :categorie_risque)
ON CONFLICT (client_id)
DO UPDATE SET
    score_credit_client = EXCLUDED.score_credit_client,
    segment_client = EXCLUDED.segment_client,
    categorie_risque = EXCLUDED.categorie_risque;
""")

print("Insertion OK")
print(engine.url)

Insertion OK
postgresql+psycopg2://postgres:***@localhost:5432/financecore_db

In [40]:
query_segments = text("""
INSERT INTO public.segments (segment_client)
VALUES (:segment_client)
ON CONFLICT (segment_client)
DO NOTHING;
""")

segments_df.to_sql("segments", engine, if_exists="append", index=False)

print("Segments OK")

Segments OK

In [41]:
segments_df

  segment_client  segment_id
0        Premium           1
1         Risque           2
2       Standard           3

In [42]:
query_comptes = text("""
INSERT INTO public.comptes (
    compte_id, client_id, solde_avant
)
VALUES (
    :compte_id, :client_id, :solde_avant
)
ON CONFLICT (compte_id)
DO UPDATE SET
    client_id = EXCLUDED.client_id,
    solde_avant = EXCLUDED.solde_avant;
""")

comptes_df.to_sql("comptes", engine, if_exists="append", index=False)

print("Comptes OK")

Comptes OK

In [43]:
query_produits = text("""
INSERT INTO public.produits (nom_produit)
VALUES (:nom_produit)
ON CONFLICT (nom_produit)
DO NOTHING;
""")

produits_df.to_sql("produits", engine, if_exists="append", index=False)

print("Produits OK")

Produits OK

In [44]:
query_agences = text("""
INSERT INTO public.agences (nom_agence)
VALUES (:nom_agence)
ON CONFLICT (nom_agence)
DO NOTHING;
""")

agences_df.to_sql("agences", engine, if_exists="append", index=False)

print("Agences OK")

Agences OK

In [45]:
query_temps = text("""
INSERT INTO public.temps (
    date_transaction, annee, mois, trimestre, jour_semaine
)
VALUES (
    :date_transaction, :annee, :mois, :trimestre, :jour_semaine
)
ON CONFLICT (date_transaction)
DO NOTHING;
""")

temps_df.to_sql("temps", engine, if_exists="append", index=False)

print("Temps OK")

Temps OK

In [46]:
query_transactions = text("""
INSERT INTO public.transactions (
    transaction_id, client_id, date_transaction,
    montant, devise, taux_change_eur, montant_eur,
    categorie, produit, agence, type_operation,
    statut, score_credit_client, segment_client,
    solde_avant, is_outlier_montant, is_outlier_score,
    is_anomaly, annee, mois, trimestre,
    jour_semaine, montant_eur_verifie,
    montant_eur_match, categorie_risque,
    montant_credit, montant_debit, rejet
)
VALUES (
    :transaction_id, :client_id, :date_transaction,
    :montant, :devise, :taux_change_eur, :montant_eur,
    :categorie, :produit, :agence, :type_operation,
    :statut, :score_credit_client, :segment_client,
    :solde_avant, :is_outlier_montant, :is_outlier_score,
    :is_anomaly, :annee, :mois, :trimestre,
    :jour_semaine, :montant_eur_verifie,
    :montant_eur_match, :categorie_risque,
    :montant_credit, :montant_debit, :rejet
)
ON CONFLICT (transaction_id)
DO NOTHING;
""")

transactions_df.to_sql("transactios", engine, if_exists="append", index=False)

print("Transactions OK")

Transactions OK

#  Étape4️⃣ Requêtes SQL Analytiques Avancées

Agrégations (GROUP BY, HAVING)

In [47]:
query_agg = """
SELECT 
    agence,
    produit,
    DATE_TRUNC('month', date_transaction::TIMESTAMP) AS mois,
    SUM(montant) AS total_transactions,
    AVG(montant) AS moyenne_transactions
FROM transactions
GROUP BY agence, produit, DATE_TRUNC('month', date_transaction::TIMESTAMP)
ORDER BY mois, agence;
"""

df_agg = pd.read_sql(query_agg, engine)
df_agg.head()

,agence,produit,mois,total_transactions,moyenne_transactions
0,Bordeaux-Meriadeck,Credit Immobilier,2022-01-01,-4966.54,-2483.270
1,Bordeaux-Meriadeck,Credit Consommation,2022-01-01,-4190.00,-2095.000
2,Bordeaux-Meriadeck,Compte Epargne,2022-01-01,-2261.90,-565.475
3,Bordeaux-Meriadeck,PEA,2022-01-01,-2914.16,-1457.080
4,Lille-Grand-Place,Credit Consommation,2022-01-01,-4756.32,-2378.160

Sous-requêtes (Clients b solde < moyenne)

In [48]:
query_sub = """
SELECT 
    client_id, 
    solde_avant
FROM comptes
WHERE solde_avant < (SELECT AVG(solde_avant) FROM comptes)
ORDER BY solde_avant DESC;
"""

df_low_balance = pd.read_sql(query_sub, engine)
df_low_balance.head()

  client_id  solde_avant
0   CLI0065     24777.26
1   CLI0065     24777.26
2   CLI0065     24777.26
3   CLI0065     24777.26
4   CLI0050     24692.61

CASE WHEN (Taux de défaut par segment)

In [49]:
query_case = """
SELECT 
    categorie_risque,
    COUNT(*) AS total_trans,
    SUM(CASE WHEN rejet = 1 THEN 1 ELSE 0 END) AS nb_rejets,
    ROUND(AVG(CASE WHEN rejet = 1 THEN 1 ELSE 0 END) * 100, 2) AS taux_rejet_pct
FROM transactions
GROUP BY categorie_risque
ORDER BY taux_rejet_pct DESC;
"""

df_risk_analysis = pd.read_sql(query_case, engine)
df_risk_analysis

  categorie_risque  total_trans  nb_rejets  taux_rejet_pct
0             High          776          0             0.0
1           Medium         2278          0             0.0
2              Low          946          0             0.0

Jointures Multi-tables

In [50]:
query_join = """
SELECT 
    cl.client_id,
    cl.score_credit_client,
    s.segment_client,
    co.solde_avant
FROM clients cl
JOIN segments s ON cl.segment_client = s.segment_client
JOIN comptes co ON cl.client_id = co.client_id
LIMIT 10;
"""

df_full_profile = pd.read_sql(query_join, engine)
df_full_profile

  client_id  score_credit_client segment_client  solde_avant
0   CLI0060                645.0        Premium     16415.10
1   CLI0060                645.0        Premium     18788.73
2   CLI0060                645.0        Premium     14964.14
3   CLI0060                645.0        Premium       885.02
4   CLI0060                645.0        Premium     18760.57
5   CLI0060                645.0        Premium     28309.09
6   CLI0060                645.0        Premium      5585.32
7   CLI0060                645.0        Premium     27037.50
8   CLI0060                645.0        Premium     22308.84
9   CLI0060                645.0        Premium     25428.16

Création de Vues Analytiques (Version Corrigée)

In [51]:
from sqlalchemy import text

view_query = text("""
CREATE OR REPLACE VIEW vue_kpi_dashboard AS
SELECT 
    t.date_transaction::DATE,
    t.agence,
    t.produit,
    SUM(t.montant) AS volume_affaires,
    COUNT(*) AS nombre_transactions,
    AVG(cl.score_credit_client) AS score_moyen_client
FROM transactions t
JOIN clients cl ON t.client_id = cl.client_id
GROUP BY t.date_transaction::DATE, t.agence, t.produit;
""")

with engine.connect() as connection:
    connection.execute(view_query)
    connection.commit()

print("Vue analytique 'vue_kpi_dashboard' créée avec succès !")

Vue analytique 'vue_kpi_dashboard' créée avec succès !